/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.project;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.sql.Date;
/**
 *
 * @author Arif Hidayat
 */
public class UangKas extends javax.swing.JFrame {
     private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, keterangan;
    private DefaultTableModel dtm;

    /**
     * Creates new form UangKas
     */
    public UangKas() {
        initComponents();
         setTitle("LAPORAN UANGKAS");
        koneksi ();
        kosongkan ();
        tabel ();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
           (screenSize.width - frameSize.width) / 3,
           (screenSize.height - frameSize.height) /4);
    }
    private void koneksi (){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
    private void kosongkan(){
     kelompok_no.setText("");
     kelompok_tanggal.setDate(null);
     kelompok_nama.setText("");
     kelompok_keterangan.setText("");
     kelompok_pembayaran.setText("");
     kelompok_pengeluaran.setText("");
     kelompok_saldoakhir.setText("");
     pembayaran.setSelected(false);
     pengeluaran.setSelected(false);
     kelompok_no.requestFocus();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("SaldoAkhir");
        t.addColumn("Keterangan");
        kelompok_table.setModel(t); try{ res= stat.executeQuery("select * from uangkas");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("SaldoAkhir"),
      res.getString("Keterangan")
        });}
    }catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kelompok_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kelompok_nama = new javax.swing.JTextField();
        kelompok_keterangan = new javax.swing.JTextField();
        pembayaran = new javax.swing.JCheckBox();
        pengeluaran = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kelompok_pembayaran = new javax.swing.JTextField();
        kelompok_pengeluaran = new javax.swing.JTextField();
        kelompok_saldoakhir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UANGKAS = new javax.swing.JTextField();
        kelompok_tanggal = new com.toedter.calendar.JDateChooser();
        kelompok_simpan = new javax.swing.JButton();
        kelompok_clear = new javax.swing.JButton();
        kelompok_hapus = new javax.swing.JButton();
        kelompok_search = new javax.swing.JButton();
        kelompok_edit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kelompok_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kelompok_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        kelompok_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_noActionPerformed(evt);
            }
        });
        kelompok_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kelompok_noKeyTyped(evt);
            }
        });

        jLabel2.setText("No.");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Nama");

        jLabel5.setText("Keterangan");

        kelompok_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_namaActionPerformed(evt);
            }
        });

        kelompok_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_keteranganActionPerformed(evt);
            }
        });

        pembayaran.setText("pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        pengeluaran.setText("pengeluaran");
        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });

        jLabel6.setText("Rp.");

        jLabel7.setText("Rp.");

        kelompok_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_pembayaranActionPerformed(evt);
            }
        });
        kelompok_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kelompok_pembayaranKeyTyped(evt);
            }
        });

        kelompok_pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kelompok_pengeluaranKeyTyped(evt);
            }
        });

        kelompok_saldoakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_saldoakhirActionPerformed(evt);
            }
        });
        kelompok_saldoakhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kelompok_saldoakhirKeyTyped(evt);
            }
        });

        jLabel8.setText("Saldo Akhir");

        jLabel9.setText("Uang kas / 1 minggu");

        UANGKAS.setText("5000");

        kelompok_simpan.setText("SIMPAN");
        kelompok_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_simpanActionPerformed(evt);
            }
        });

        kelompok_clear.setText("CLEAR");
        kelompok_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_clearActionPerformed(evt);
            }
        });

        kelompok_hapus.setText("HAPUS");
        kelompok_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_hapusActionPerformed(evt);
            }
        });

        kelompok_search.setText("SEARCH");
        kelompok_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_searchActionPerformed(evt);
            }
        });

        kelompok_edit.setText("EDIT");
        kelompok_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_editActionPerformed(evt);
            }
        });

        jButton1.setText("LIHAT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kelompok_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelompok_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kelompok_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kelompok_hapus)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kelompok_search)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pembayaran)
                                    .addComponent(pengeluaran))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6))
                                        .addGap(0, 73, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelompok_keterangan)
                            .addComponent(kelompok_no)
                            .addComponent(kelompok_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(kelompok_nama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kelompok_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UANGKAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(kelompok_saldoakhir)
                            .addComponent(kelompok_pengeluaran))
                        .addGap(169, 169, 169))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kelompok_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pembayaran)
                                .addComponent(jLabel6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(pengeluaran))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(kelompok_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(kelompok_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(kelompok_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kelompok_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(kelompok_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kelompok_saldoakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(UANGKAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelompok_simpan)
                    .addComponent(kelompok_clear)
                    .addComponent(kelompok_hapus)
                    .addComponent(kelompok_search)
                    .addComponent(kelompok_edit))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("LAPORAN KEUANGAN KAS KELAS");

        kelompok_back.setText("BACK");
        kelompok_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelompok_backActionPerformed(evt);
            }
        });

        kelompok_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kelompok_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelompok_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kelompok_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(179, 179, 179)
                                .addComponent(kelompok_back)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kelompok_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        keterangan = "Uang Masuk";
        pengeluaran.setSelected(false);
        kelompok_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void kelompok_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_backActionPerformed
        // TODO add your handling code here:
        new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_kelompok_backActionPerformed

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
         keterangan = "Pengeluaran";
        pembayaran.setSelected(false);
        kelompok_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pengeluaranActionPerformed

    private void kelompok_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_noActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from uangkas where "+ "No='" + kelompok_no.getText()
                +"'" ); while (res.next())
                { kelompok_tanggal.setDate (res.getDate("Tanggal"));
                kelompok_nama.setText(res.getString("Nama"));
                kelompok_pembayaran.setText(res.getString("Pemasukan"));
                kelompok_pengeluaran.setText(res.getString("Pengeluaran"));
                kelompok_saldoakhir.setText(res.getString("SaldoAkhir"));
                kelompok_keterangan.setText(res.getString("Keterangan"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_kelompok_noActionPerformed

    private void kelompok_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_simpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(kelompok_tanggal.getDate()));
        
        try {
         stat.executeUpdate("insert into uangkas values ("
             + "'" + kelompok_no.getText()+"',"
             + "'" + Tanggal+"',"
             + "'" + kelompok_nama.getText()+"',"
             + "'" + kelompok_keterangan.getText()+"',"
             + "'" + kelompok_pembayaran.getText()+"',"
             + "'" + kelompok_pengeluaran.getText()+"',"
             + "'" + kelompok_saldoakhir.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new UangKas().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_kelompok_simpanActionPerformed

    private void kelompok_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_editActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin mengedit data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(kelompok_tanggal.getDate()));
    try{
    String sql = "update uangkas set No=?,Tanggal=?,Nama=?,Pemasukan=?,Pengeluaran=?,"
            + "SaldoAkhir=?,Keterangan=? where No='"
                    + kelompok_no.getText()+"'";
    PreparedStatement st=con.prepareStatement(sql);
    if(ok==0){
    try{
    st.setString(1,kelompok_no.getText());
    st.setString(2,Tanggal);
    st.setString(3,kelompok_nama.getText());
    st.setString(4,kelompok_pembayaran.getText());
    st.setString(5,kelompok_pengeluaran.getText());
    st.setString(6,kelompok_saldoakhir.getText());
    st.setString(7,kelompok_keterangan.getText());
    st.executeUpdate();
    kosongkan();
    JOptionPane.showMessageDialog(null,"Edit Data Sukses");
    new UangKas().setVisible(true);
    dispose();
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, "Edit Data Gagal");}}
    }catch (Exception e){}
    }//GEN-LAST:event_kelompok_editActionPerformed

    private void kelompok_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_clearActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_kelompok_clearActionPerformed

    private void kelompok_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_hapusActionPerformed
        // TODO add your handling code here:
         int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from uangkas where No='"+kelompok_no.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new UangKas().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_kelompok_hapusActionPerformed

    private void kelompok_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_searchActionPerformed
        // TODO add your handling code here:
        try {
    res=stat.executeQuery("select * from uangkas where "+ "No='" +kelompok_no.getText()
    +"'" ); while (res.next())
    { kelompok_tanggal.setDate(res.getDate("Tanggal"));
      kelompok_nama.setText(res.getString("Nama"));
      kelompok_pembayaran.setText(res.getString("Pemasukan"));
      kelompok_pengeluaran.setText(res.getString("Pengeluaran"));
      kelompok_saldoakhir.setText(res.getString("SaldoAkhir"));
      kelompok_keterangan.setText(res.getString("Keterangan"));
    }
    }catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_kelompok_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kelompok_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelompok_tableMouseClicked
        // TODO add your handling code here:
        int i = kelompok_table.getSelectedRow();
    if(i==-1){
    return;
    }
    String code = (String)kelompok_table.getValueAt(i,0);
    String code1 = (String)kelompok_table.getValueAt(i,1);
    String code2 = (String)kelompok_table.getValueAt(i,2);
    String code3 = (String)kelompok_table.getValueAt(i,3);
    String code4 = (String)kelompok_table.getValueAt(i,4);
    String code5 = (String)kelompok_table.getValueAt(i,5);
    String code6 = (String)kelompok_table.getValueAt(i,6);
    
    kelompok_no.setText(code);
    kelompok_tanggal.setDateFormatString(code1);
    kelompok_nama.setText(code2);
    kelompok_pembayaran.setText(code3);
    kelompok_pengeluaran.setText(code4);
    kelompok_saldoakhir.setText(code5);
    kelompok_keterangan.setText(code6);
    }//GEN-LAST:event_kelompok_tableMouseClicked

    private void kelompok_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelompok_pembayaranActionPerformed

    private void kelompok_pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelompok_pembayaranKeyTyped
        // TODO add your handling code here:
         char kelompok=evt.getKeyChar();
        if(!(Character.isDigit(kelompok)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_kelompok_pembayaranKeyTyped

    private void kelompok_pengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelompok_pengeluaranKeyTyped
        // TODO add your handling code here:
        char kelompok=evt.getKeyChar();
        if(!(Character.isDigit(kelompok)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_kelompok_pengeluaranKeyTyped

    private void kelompok_saldoakhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelompok_saldoakhirKeyTyped
        // TODO add your handling code here:
        char kelompok=evt.getKeyChar();
        if(!(Character.isDigit(kelompok)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_kelompok_saldoakhirKeyTyped

    private void kelompok_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelompok_noKeyTyped
        // TODO add your handling code here:
        char kelompok=evt.getKeyChar();
        if(!(Character.isDigit(kelompok)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_kelompok_noKeyTyped

    private void kelompok_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelompok_keteranganActionPerformed

    private void kelompok_saldoakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_saldoakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelompok_saldoakhirActionPerformed

    private void kelompok_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelompok_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelompok_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangKas().setVisible(true);
            }
        });
    }

    class kelompok_nama {

        public kelompok_nama() {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UANGKAS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelompok_back;
    private javax.swing.JButton kelompok_clear;
    private javax.swing.JButton kelompok_edit;
    private javax.swing.JButton kelompok_hapus;
    private javax.swing.JTextField kelompok_keterangan;
    public javax.swing.JTextField kelompok_nama;
    private javax.swing.JTextField kelompok_no;
    private javax.swing.JTextField kelompok_pembayaran;
    private javax.swing.JTextField kelompok_pengeluaran;
    private javax.swing.JTextField kelompok_saldoakhir;
    private javax.swing.JButton kelompok_search;
    private javax.swing.JButton kelompok_simpan;
    private javax.swing.JTable kelompok_table;
    private com.toedter.calendar.JDateChooser kelompok_tanggal;
    private javax.swing.JCheckBox pembayaran;
    private javax.swing.JCheckBox pengeluaran;
    // End of variables declaration//GEN-END:variables
}
